port: 3000
mongodb:
  connection: "mongodb://localhost:27019/express-login-demo"
session:
  secret: "express-login-demo-session-secret"
  cookie:
    maxAge: 60000 # 60 * 1000
  mongodb:
    connection: "mongodb://localhost:27019/express-login-demo-session"
    collection: "session"
